name: metafy_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^5.0.0-nullsafety.5
  json_annotation: ^4.0.1
  mask_text_input_formatter: ^2.0.0
  package_info_plus: ^1.0.3
  image_picker: ^0.8.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_launcher_icons: "^0.9.0"
  flutter_lints: ^1.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo-icon.png"
  image_path_android: "assets/images/logo-icon.png"
  adaptive_icon_background: "assets/images/logo-icon.png"
  adaptive_icon_foreground: "assets/images/logo-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo-icon.png
    - assets/images/logo-t.png
    - assets/images/logo-icon-t.png
    - assets/images/background.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
